sudo: required
language: go
services:
  - docker

go:
  - 1.x
  - 1.7

before_install:
  - curl https://glide.sh/get | sh
  - docker-compose -f assets/docker-compose.yml up -d

install:
  - mkdir -p $GOPATH/bin
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls
  - make deps

script:
- make test-integration
- $GOPATH/bin/overalls -project=github.com/hellofresh/janus -covermode=count
- if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then bash <(curl -s https://codecov.io/bash) -f overalls.coverprofile; fi
- if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN; fi
