################################################################
# Global configuration
################################################################
port = 8080
logLevel = "debug"

################################################################
# API configuration backend
################################################################
[web]
  port = 8081

  [credentials]
    secret = "secret key"
    username = "admin"
    password = "admin"

[database]
  dsn = "file:///etc/janus"
