# This file is used to run integration tests on travis
version: '2'
services:

  janus-database:
      image: mongo:3
      ports:
          - "27017:27017"
          
  service1:
    image: rodolpheche/wiremock:2.6.0-alpine
    ports:
      - '9089:8080'
    volumes:
      - ./stubs:/home/wiremock

  auth-service:
    image: rodolpheche/wiremock:2.6.0-alpine
    ports:
      - '9088:8080'
    volumes:
      - ./stubs/auth:/home/wiremock/mappings

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"

  zipkin:
    image: openzipkin/zipkin
    environment:
      STORAGE_TYPE: mem
      JAVA_OPTS: -Dlogging.level.zipkin=DEBUG
    ports:
      - 9411:9411
