################################################################
# Clustering
################################################################
[cluster]
  UpdateFrequency = "1s"

[log]
   level = "debug"
   format = "json"
   writer = "stderr"

[web]

  [web.credentials]
    # The algorithm that you want to use to create your JWT
    algorithm = "HS256"
    # This is the secret that you will use to encrypt your JWT
    secret = "secret key"

    [web.credentials.github]
      organizations = ["umbrellaTech"]
      teams = {umbrellaTech = "scientists"}

[database]
  dsn = "mongodb://localhost:27017/janus"

[stats]
   dsn = "noop://"

[tracing]
  provider = "jaeger"
  [tracing.jaeger]
    SamplingServerURL = "localhost:6832"
